[package]
name = "aoc-2022-rust"
version = "0.1.0"
edition = "2021"
authors = ["Matt Cordes <matt.cordes@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "day1"
